name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.8.1
  - ca-certificates
  - certifi
  - charset-normalizer
  - colorama
  - contourpy
  - cycler
  - filelock
  - fonttools
  - freetype
  - fsspec
  - idna
  - ipython
  - jedi
  - jinja2
  - joblib
  - jpeg
  - kiwisolver
  - lcms2
  - lerc
  - libblas
  - libcblas
  - libdeflate
  - libffi
  - liblapack
  - libpng
  - libsqlite
  - libtiff
  - libwebp
  - libzlib
  - markupsafe
  - matplotlib
  - matplotlib-inline
  - mkl
  - munkres
  - nest-asyncio
  - networkx
  - numpy
  - openh264
  - openssl
  - packaging
  - pandas
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - pure_eval
  - pygments
  - python=3.12
  - python-dateutil
  - python_abi
  - pytorch
  - pytz
  - pyzmq
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - six
  - stack_data
  - threadpoolctl
  - tk
  - torchaudio
  - torchvision
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zlib
  - pip:
      - ffmpeg-python
