name: VCA
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aom=3.8.1
  - asttokens=3.0.0
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cairo=1.18.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - contourpy=1.3.2
  - cycler=0.12.1
  - dav1d=1.2.1
  - decorator=5.2.1
  - deprecated=1.2.18
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - ffmpeg=6.1.1
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.1
  - freeglut=3.4.0
  - freetype=2.12.1
  - fsspec=2025.5.1
  - giflib=5.2.2
  - graphite2=1.3.14
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.6.1
  - intel-openmp=2023.2.0
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libdeflate=1.22
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=15.1.0
  - libglib=2.80.2
  - libgomp=15.1.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libogg=1.3.5
  - libpng=1.6.43
  - libpq=17.0
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libsqlite=3.50.0
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuv=1.51.0
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.8
  - libxslt=1.1.41
  - libzlib=1.2.13
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - minizip=4.0.6
  - mkl=2023.2.0
  - mkl-service=2.4.1
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.6.0
  - openjpeg=2.5.2
  - openssl=3.5.0
  - opentelemetry-api=1.33.1
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1.1
  - pixman=0.46.0
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytorch=2.5.1
  - pytz=2025.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.3
  - qtwebsockets=6.7.3
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.8
  - sqlite=3.50.0
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.13
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - wrapt=1.17.2
  - xz=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.22.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - click==8.2.1
      - git+https://github.com/openai/CLIP.git
      - dataclasses-json==0.6.7
      - dnspython==2.7.0
      - email-validator==2.2.0
      - faiss-cpu==1.11.0
      - fastapi==0.115.12
      - fastapi-cli==0.0.7
      - ffmpeg-python==0.2.0
      - frozenlist==1.6.2
      - ftfy==6.3.1
      - future==1.0.0
      - greenlet==3.2.3
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.32.4
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.25
      - langchain-community==0.3.24
      - langchain-core==0.3.64
      - langchain-text-splitters==0.3.8
      - langsmith==0.3.45
      - markdown-it-py==3.0.0
      - marshmallow==3.26.1
      - mdurl==0.1.2
      - multidict==6.4.4
      - mypy-extensions==1.1.0
      - opencv-python==4.11.0.86
      - orjson==3.10.18
      - propcache==0.3.1
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydantic-settings==2.9.1
      - python-dotenv==1.1.0
      - python-multipart==0.0.20
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - rich-toolkit==0.14.7
      - safetensors==0.5.3
      - sentence-transformers==4.1.0
      - shellingham==1.5.4
      - sniffio==1.3.1
      - sqlalchemy==2.0.41
      - starlette==0.46.2
      - tenacity==9.1.2
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - transformers==4.52.4
      - typer==0.16.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - uvicorn==0.34.3
      - watchfiles==1.0.5
      - websockets==15.0.1
      - yarl==1.20.0